[features]
seeds = false
[programs.localnet]
mycalcdapp = "GbgR8ovmXQbW5E64KCLtd5AUnvoBQgtN9vjMHvFSzEaf"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/kreolx/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
